/**
 * HMAC-SHA256 signing for master.json snapshots.
 *
 * Thin re-export over `@0711/envelope`. Lives here so existing sturm imports
 * (`import { … } from '../../lib/master-signer.ts'`) keep working without a
 * rewrite. The actual implementation — and the cross-project envelope (v2)
 * with project-binding — sits in `packages/envelope/`.
 *
 * For new code prefer the v2 envelope (signEnvelope/verifyEnvelope) directly
 * from `@0711/envelope`. Use this module only when extending sturm's existing
 * master.json signing path.
 */

import { resolveSharedKey } from '../../packages/envelope/src/keys.ts';

export { signMaster, verifyMaster } from '../../packages/envelope/src/master.ts';
export type { MasterSignature, VerifyResult } from '../../packages/envelope/src/master.ts';

/** Sturm-flavored shared-key resolver. Env `STURM_MASTER_HMAC_KEY` first,
 *  then `.master-key.json` in rootDir, else autogenerated + persisted. */
export function resolveMasterKey(rootDir: string): Promise<string> {
  return resolveSharedKey({
    envVar: 'STURM_MASTER_HMAC_KEY',
    keyFile: '.master-key.json',
    rootDir,
  });
}
