#!/usr/bin/env bash
# Refresh deploy/cloudflare/routes.yaml from the live Cloudflare API.
#
# Usage:
#   CF_EMAIL=c@camm.org CF_KEY=<global-key> deploy/cloudflare/refresh-routes.sh [--diff]
#
# Without --diff: writes routes.yaml in place.
# With --diff:    prints a unified diff against the committed file and exits
#                 with code 1 if there's drift (CI gate).
#
# Phase F.2 / Task 8.
set -euo pipefail

if [[ -z "${CF_EMAIL:-}" || -z "${CF_KEY:-}" ]]; then
  echo "error: CF_EMAIL and CF_KEY must be set (load from your secret manager)" >&2
  exit 2
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required" >&2
  exit 2
fi

CF_BASE="https://api.cloudflare.com/client/v4"
HEADERS=(-H "X-Auth-Email: $CF_EMAIL" -H "X-Auth-Key: $CF_KEY")

ACCOUNT_ID=$(curl -sS "${HEADERS[@]}" "$CF_BASE/accounts" | jq -r '.result[0].id')
if [[ -z "$ACCOUNT_ID" || "$ACCOUNT_ID" == "null" ]]; then
  echo "error: could not resolve account id (token rotated?)" >&2
  exit 2
fi

OUT="$(mktemp)"
trap 'rm -f "$OUT"' EXIT

{
  echo "# Cloudflare Tunnel route map — auto-generated by refresh-routes.sh."
  echo "# Edit Cloudflare and re-run this script; do not hand-edit."
  echo "tunnels:"

  curl -sS "${HEADERS[@]}" \
    "$CF_BASE/accounts/$ACCOUNT_ID/cfd_tunnel?is_deleted=false&per_page=200" \
  | jq -r '.result[] | [.id, .name, .status, .config_src] | @tsv' \
  | while IFS=$'\t' read -r tid tname tstatus tcfgsrc; do
      echo "  - name: $tname"
      echo "    id: $tid"
      echo "    status: $tstatus"
      echo "    config_src: $tcfgsrc"
      echo "    routes:"
      curl -sS "${HEADERS[@]}" \
        "$CF_BASE/accounts/$ACCOUNT_ID/cfd_tunnel/$tid/configurations" \
      | jq -r '.result.config.ingress[]? | select(.hostname) | "      - hostname: \(.hostname)\n        service: \(.service)"'
    done
} > "$OUT"

if [[ "${1:-}" == "--diff" ]]; then
  if diff -u deploy/cloudflare/routes.yaml "$OUT"; then
    echo "✓ routes.yaml matches Cloudflare"
    exit 0
  else
    echo "✗ drift detected — re-run without --diff to apply"
    exit 1
  fi
else
  cp "$OUT" deploy/cloudflare/routes.yaml
  echo "wrote deploy/cloudflare/routes.yaml ($(wc -l < deploy/cloudflare/routes.yaml) lines)"
fi
